# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_records_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(778, 473)
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(Form)
        self.title.setStyleSheet("font: 75 16pt \"微软雅黑\";")
        self.title.setIndent(24)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(24, 6, -1, 6)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.comboBoxLine = MyQComboBox(Form)
        self.comboBoxLine.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxLine.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.comboBoxLine.setObjectName("comboBoxLine")
        self.horizontalLayout_2.addWidget(self.comboBoxLine)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.comboBoxPart = MyQComboBox(Form)
        self.comboBoxPart.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBoxPart.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.comboBoxPart.setObjectName("comboBoxPart")
        self.horizontalLayout_2.addWidget(self.comboBoxPart)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.comboBoxLocation = MyQComboBox(Form)
        self.comboBoxLocation.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxLocation.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxLocation.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.comboBoxLocation.setObjectName("comboBoxLocation")
        self.horizontalLayout_2.addWidget(self.comboBoxLocation)
        self.checkBoxResult = QtWidgets.QCheckBox(Form)
        self.checkBoxResult.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.checkBoxResult.setObjectName("checkBoxResult")
        self.horizontalLayout_2.addWidget(self.checkBoxResult)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(7, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(24, 6, -1, 6)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBack = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBack.sizePolicy().hasHeightForWidth())
        self.buttonBack.setSizePolicy(sizePolicy)
        self.buttonBack.setMinimumSize(QtCore.QSize(60, 0))
        self.buttonBack.setMaximumSize(QtCore.QSize(60, 16777215))
        self.buttonBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBack.setStyleSheet("QPushButton{\n"
"    font: 75 9pt \"微软雅黑\";\n"
"    text-decoration: underline;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 170, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 170, 255);\n"
"    border:none;\n"
"}")
        self.buttonBack.setFlat(True)
        self.buttonBack.setObjectName("buttonBack")
        self.horizontalLayout.addWidget(self.buttonBack)
        self.buttonNext = QtWidgets.QPushButton(Form)
        self.buttonNext.setMinimumSize(QtCore.QSize(60, 0))
        self.buttonNext.setMaximumSize(QtCore.QSize(60, 16777215))
        self.buttonNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonNext.setStyleSheet("QPushButton{\n"
"    font: 75 9pt \"微软雅黑\";\n"
"    text-decoration: underline;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 170, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 170, 255);\n"
"    border:none;\n"
"}")
        self.buttonNext.setFlat(True)
        self.buttonNext.setObjectName("buttonNext")
        self.horizontalLayout.addWidget(self.buttonNext)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBoxPage = QtWidgets.QSpinBox(Form)
        self.spinBoxPage.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxPage.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.spinBoxPage.setMinimum(1)
        self.spinBoxPage.setMaximum(99)
        self.spinBoxPage.setObjectName("spinBoxPage")
        self.horizontalLayout.addWidget(self.spinBoxPage)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelPages = QtWidgets.QLabel(Form)
        self.labelPages.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.labelPages.setObjectName("labelPages")
        self.horizontalLayout.addWidget(self.labelPages)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBoxPageRows = QtWidgets.QSpinBox(Form)
        self.spinBoxPageRows.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxPageRows.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.spinBoxPageRows.setMinimum(5)
        self.spinBoxPageRows.setMaximum(24)
        self.spinBoxPageRows.setProperty("value", 10)
        self.spinBoxPageRows.setObjectName("spinBoxPageRows")
        self.horizontalLayout.addWidget(self.spinBoxPageRows)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(8, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableRecords = MyQTableWidget(Form)
        self.tableRecords.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableRecords.setMouseTracking(True)
        self.tableRecords.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableRecords.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableRecords.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableRecords.setAutoScroll(True)
        self.tableRecords.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableRecords.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableRecords.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableRecords.setColumnCount(0)
        self.tableRecords.setObjectName("tableRecords")
        self.tableRecords.setRowCount(0)
        self.tableRecords.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableRecords)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "历史记录列表"))
        self.label_8.setText(_translate("Form", "生产线"))
        self.label_9.setText(_translate("Form", "零件"))
        self.label_10.setText(_translate("Form", "位置"))
        self.checkBoxResult.setText(_translate("Form", "只显示错误"))
        self.buttonBack.setText(_translate("Form", "上一页"))
        self.buttonNext.setText(_translate("Form", "下一页"))
        self.label_3.setText(_translate("Form", "当前页："))
        self.label.setText(_translate("Form", "总页数："))
        self.labelPages.setText(_translate("Form", "2"))
        self.label_4.setText(_translate("Form", "每页显示："))
        self.tableRecords.setSortingEnabled(True)
from Interface.my_promote_widget import MyQComboBox, MyQTableWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
