# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_show_part_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(680, 880)
        Dialog.setMinimumSize(QtCore.QSize(580, 880))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditLine = QtWidgets.QLineEdit(Dialog)
        self.lineEditLine.setEnabled(False)
        self.lineEditLine.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEditLine.setObjectName("lineEditLine")
        self.gridLayout.addWidget(self.lineEditLine, 0, 1, 1, 1)
        self.lineEditColumns = QtWidgets.QLineEdit(Dialog)
        self.lineEditColumns.setEnabled(False)
        self.lineEditColumns.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEditColumns.setObjectName("lineEditColumns")
        self.gridLayout.addWidget(self.lineEditColumns, 1, 3, 1, 1)
        self.tablePins = QtWidgets.QTableWidget(Dialog)
        self.tablePins.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tablePins.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tablePins.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablePins.setAutoScroll(True)
        self.tablePins.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablePins.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tablePins.setObjectName("tablePins")
        self.tablePins.setColumnCount(0)
        self.tablePins.setRowCount(0)
        self.tablePins.horizontalHeader().setDefaultSectionSize(30)
        self.tablePins.verticalHeader().setMinimumSectionSize(24)
        self.gridLayout.addWidget(self.tablePins, 2, 0, 1, 4)
        self.lineEditRows = QtWidgets.QLineEdit(Dialog)
        self.lineEditRows.setEnabled(False)
        self.lineEditRows.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEditRows.setObjectName("lineEditRows")
        self.gridLayout.addWidget(self.lineEditRows, 1, 1, 1, 1)
        self.labelPart = QtWidgets.QLabel(Dialog)
        self.labelPart.setMinimumSize(QtCore.QSize(50, 20))
        self.labelPart.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.labelPart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPart.setObjectName("labelPart")
        self.gridLayout.addWidget(self.labelPart, 0, 2, 1, 1)
        self.labelRows = QtWidgets.QLabel(Dialog)
        self.labelRows.setMinimumSize(QtCore.QSize(50, 20))
        self.labelRows.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.labelRows.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRows.setObjectName("labelRows")
        self.gridLayout.addWidget(self.labelRows, 1, 0, 1, 1)
        self.lineEditPart = QtWidgets.QLineEdit(Dialog)
        self.lineEditPart.setEnabled(False)
        self.lineEditPart.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEditPart.setObjectName("lineEditPart")
        self.gridLayout.addWidget(self.lineEditPart, 0, 3, 1, 1)
        self.labelColumns = QtWidgets.QLabel(Dialog)
        self.labelColumns.setMinimumSize(QtCore.QSize(50, 20))
        self.labelColumns.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.labelColumns.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelColumns.setObjectName("labelColumns")
        self.gridLayout.addWidget(self.labelColumns, 1, 2, 1, 1)
        self.labelLine = QtWidgets.QLabel(Dialog)
        self.labelLine.setMinimumSize(QtCore.QSize(50, 20))
        self.labelLine.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.labelLine.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelLine.setObjectName("labelLine")
        self.gridLayout.addWidget(self.labelLine, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "零件详细"))
        self.labelPart.setText(_translate("Dialog", "零件号："))
        self.labelRows.setText(_translate("Dialog", "顶棒行数："))
        self.labelColumns.setText(_translate("Dialog", "顶棒列数："))
        self.labelLine.setText(_translate("Dialog", "生产线："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
