# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_cameras_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(778, 473)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(Form)
        self.title.setStyleSheet("font: 75 16pt \"微软雅黑\";")
        self.title.setIndent(24)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(24, 6, -1, 6)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonOpen = QtWidgets.QPushButton(Form)
        self.buttonOpen.setEnabled(False)
        self.buttonOpen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonOpen.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.buttonOpen.setObjectName("buttonOpen")
        self.horizontalLayout.addWidget(self.buttonOpen)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableCameras = MyQTableWidget(Form)
        self.tableCameras.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableCameras.setMouseTracking(True)
        self.tableCameras.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableCameras.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableCameras.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableCameras.setAutoScroll(True)
        self.tableCameras.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCameras.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableCameras.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableCameras.setRowCount(0)
        self.tableCameras.setColumnCount(0)
        self.tableCameras.setObjectName("tableCameras")
        self.tableCameras.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableCameras)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "相机列表"))
        self.buttonOpen.setText(_translate("Form", "打开相机"))
        self.tableCameras.setSortingEnabled(True)
from Interface.my_promote_widget import MyQTableWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
