# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_root.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setMinimumSize(QtCore.QSize(0, 60))
        self.title.setMaximumSize(QtCore.QSize(16777215, 60))
        self.title.setAutoFillBackground(False)
        self.title.setStyleSheet("font: 75 20pt \"微软雅黑\";")
        self.title.setTextFormat(QtCore.Qt.PlainText)
        self.title.setWordWrap(False)
        self.title.setIndent(50)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout.addWidget(self.line_1)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.buttonCameras = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCameras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCameras.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.buttonCameras.setStyleSheet("QPushButton{\n"
"    font: 75 12pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"    border:none;\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"    border:none;\n"
"}")
        self.buttonCameras.setCheckable(True)
        self.buttonCameras.setChecked(True)
        self.buttonCameras.setAutoExclusive(True)
        self.buttonCameras.setFlat(True)
        self.buttonCameras.setObjectName("buttonCameras")
        self.verticalLayout_1.addWidget(self.buttonCameras)
        self.buttonParts = QtWidgets.QPushButton(self.centralwidget)
        self.buttonParts.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonParts.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.buttonParts.setAutoFillBackground(False)
        self.buttonParts.setStyleSheet("QPushButton{\n"
"    font: 75 12pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"    border:none;\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"    border:none;\n"
"}")
        self.buttonParts.setCheckable(True)
        self.buttonParts.setAutoExclusive(True)
        self.buttonParts.setFlat(True)
        self.buttonParts.setObjectName("buttonParts")
        self.verticalLayout_1.addWidget(self.buttonParts)
        self.buttonRecords = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRecords.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonRecords.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.buttonRecords.setAutoFillBackground(False)
        self.buttonRecords.setStyleSheet("QPushButton{\n"
"    font: 75 12pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"    border:none;\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"    border:none;\n"
"}")
        self.buttonRecords.setCheckable(True)
        self.buttonRecords.setAutoExclusive(True)
        self.buttonRecords.setFlat(True)
        self.buttonRecords.setObjectName("buttonRecords")
        self.verticalLayout_1.addWidget(self.buttonRecords)
        self.buttonSocket = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSocket.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonSocket.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.buttonSocket.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonSocket.setAutoFillBackground(False)
        self.buttonSocket.setStyleSheet("QPushButton{\n"
"    font: 75 12pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"    border:none;\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"    border:none;\n"
"}")
        self.buttonSocket.setCheckable(True)
        self.buttonSocket.setAutoExclusive(True)
        self.buttonSocket.setFlat(True)
        self.buttonSocket.setObjectName("buttonSocket")
        self.verticalLayout_1.addWidget(self.buttonSocket)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem)
        self.verticalLayout_1.setStretch(4, 1)
        self.horizontalLayout_1.addLayout(self.verticalLayout_1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_1.addWidget(self.line_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_1.addWidget(self.widget)
        self.horizontalLayout_1.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuSet = QtWidgets.QMenu(self.menubar)
        self.menuSet.setObjectName("menuSet")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReadMe = QtWidgets.QAction(MainWindow)
        self.actionReadMe.setObjectName("actionReadMe")
        self.menuSet.addAction(self.actionImport)
        self.menuSet.addSeparator()
        self.menuSet.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionReadMe)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSet.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.buttonCameras, self.buttonParts)
        MainWindow.setTabOrder(self.buttonParts, self.buttonRecords)
        MainWindow.setTabOrder(self.buttonRecords, self.widget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "冲压拉深垫顶棒视觉防错"))
        self.buttonCameras.setText(_translate("MainWindow", "相机"))
        self.buttonParts.setText(_translate("MainWindow", "零件"))
        self.buttonRecords.setText(_translate("MainWindow", "记录"))
        self.buttonSocket.setText(_translate("MainWindow", "远程"))
        self.menuSet.setTitle(_translate("MainWindow", "设置"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionImport.setText(_translate("MainWindow", "批量导入工艺文件"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))
        self.actionReadMe.setText(_translate("MainWindow", "操作手册"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
