# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_parts_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(778, 473)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(Form)
        self.title.setStyleSheet("font: 75 16pt \"微软雅黑\";")
        self.title.setIndent(24)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(24, 6, -1, 6)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxLine = MyQComboBox(Form)
        self.comboBoxLine.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBoxLine.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.comboBoxLine.setObjectName("comboBoxLine")
        self.horizontalLayout.addWidget(self.comboBoxLine)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableParts = MyQTableWidget(Form)
        self.tableParts.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableParts.setMouseTracking(True)
        self.tableParts.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableParts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableParts.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableParts.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableParts.setAutoScroll(True)
        self.tableParts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableParts.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableParts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableParts.setColumnCount(0)
        self.tableParts.setObjectName("tableParts")
        self.tableParts.setRowCount(0)
        self.tableParts.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableParts)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "零件列表"))
        self.label.setText(_translate("Form", "生产线"))
        self.tableParts.setSortingEnabled(True)
from Interface.my_promote_widget import MyQComboBox, MyQTableWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
